version: 'latest'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html
    networks:
      - mynetwork
  db:
    image: postgres:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ccpur_college
      MYSQL_USER: postgres
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - mynetwork